version: 2

builds:
  - id: linuxbuild-amd
    main: main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
  
  - id: linuxbuild-arm
    main: main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - arm64

  - id: macbuild
    main: main.go
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64

  - id: winbuild
    main: main.go
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - formats: [ tar.gz, binary ]
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [ zip, binary ]

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

nfpms:
  - id: linuxbuild-amd-nfpms
    ids:
      - linuxbuild-amd
    package_name: "tlsniff"
    description: "tlsniff - A certificate information tool"
    vendor: "OSSign"
    maintainer: OSSign <contact@ossign.org>
    file_name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}amd64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    formats:
      - deb
      - apk
      - rpm
    bindir: /usr/local/bin

  - id: linuxbuild-arm-nfpms
    ids:
      - linuxbuild-arm
    package_name: "tlsniff"
    description: "tlsniff - A certificate information tool"
    vendor: "OSSign"
    maintainer: OSSign <contact@ossign.org>
    file_name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}amd64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    formats:
      - deb
      - apk
      - rpm
    bindir: /usr/local/bin

binary_signs:
  - id: tlsniff
    ids:
      - winbuild
    cmd: ossign
    signature: "${artifact}"
    args:
      - "-o"
      - ${artifact}
      - "-t"
      - "pecoff"
      - ${artifact}

notarize:
  macos:
    - enabled: true
      ids:
        - macbuild
      sign:
        certificate: "{{ .Env.MACOS_SIGN_P12 }}"
        password: "{{ .Env.MACOS_SIGN_PASSWORD }}"
        entitlements: ./entitlements.plist
      
      notarize:
        issuer_id: "{{ .Env.MACOS_NOTARY_ISSUER_ID }}"
        key_id: "{{ .Env.MACOS_NOTARY_KEY_ID }}"
        key: "{{ .Env.MACOS_NOTARY_KEY }}"
        wait: true
        timeout: 20m

release:
  github:
    owner: ossign
    name: tlsniff

uploads:
  - name: "debpkg-amd"
    ids: ["linuxbuild-amd-nfpms"]
    method: "PUT"
    exts:
      - deb
    mode: archive
    username: "ossign-dev"
    target: https://pkg.ossign.org/debian/pool/all/main/upload
    custom_artifact_name: true
  
  - name: "apkpkg-amd"
    method: "PUT"
    ids: ["linuxbuild-amd-nfpms"]
    exts:
      - apk
    mode: archive
    username: "ossign-dev"
    target: https://pkg.ossign.org/alpine/all/repository
    custom_artifact_name: true
  
  - name: "rpmpkg-amd"
    method: "PUT"
    ids: ["linuxbuild-amd-nfpms"]
    exts:
      - rpm
    mode: archive
    username: "ossign-dev"
    target: https://pkg.ossign.org/rpm/upload
    custom_artifact_name: true
